### ISSUE TITLE
Uncaught Error: Call to a member function fetch() on null

### ISSUE THREAD

**Issue by bgreiner** [orsee/orsee#284]
<b>Author: Charlie</b>

[25-Dec-2019 00:29:56 America/Indiana/Indianapolis] PHP Fatal error:  Uncaught Error: Call to a member function fetch() on null in /groups/orsee/web/tagsets/orsee_mysql.php:129

Stack trace:

#0 /groups/orsee/web/tagsets/options.php(10): pdo_fetch_assoc(NULL)

#1 /groups/orsee/web/public/header.php(12): load_settings()

#2 /groups/orsee/web/public/index.php(7): include('/groups/orsee/w...')

#3 {main}

  thrown in /groups/orsee/web/tagsets/orsee_mysql.php on line 129

**Comment by bgreiner** [comment]
<b>Author: Ben Greiner</b>

Hi Charlie,

Could you please provide a few more details about how this error comes about. At first sight, it looks like the database is not existent (so it cannot load the settings and options, which is the first thing it usually does).

So did you have ORSEE running, and this happened suddenly? Or are you in the process of installing ORSEE, and this is the first thing you see? If the latter: have you imported the default database (install.sql)?

Cheers

/ben

**Comment by bgreiner** [comment]
<b>Author: Charlie</b>

We recently moved from ORSEE 2 to ORSEE 3. Followed all the migration

directions, did the initial larger export/import, then just the participant

export/import after everything looked good and did the final switch on the

20th. I've had ORSEE 3 in test for a few months without this error, just no cron

job. This error has only appeared once, after the switch, and it was in the

PHP logs.

I've also receive the following error twice, which was sent from the cron

job via email, but the time doesn't match with the error above. Seems to be

a mySQL value that needs increased, so I emailed the DB admins to see what

they can do.

<BR><table class="or_message" style="border-color: ; background: ; color: ">

                            <tr valign=top>

                            <td align=right><b>message:

                            </b></td>

                            <td align=left>

                            <pre>Query error: SQLSTATE[HY000]: General

error: 1615 Prepared statement needs to be re-prepared

Query: SELECT * FROM or_options

    WHERE option_type='general' OR option_type='default'</pre>

                            </td>

                            </tr>

                </tr>

                </table>
