### ISSUE TITLE
Set of conditions empty for filtering participants 

### ISSUE THREAD

**Issue by bgreiner** [orsee/orsee#304]
<b>Author: Behnud Mir Djawadi</b>

Dear all,

we encountered the following problem with our Orsee 3.1.0 version. Normally on the page for

assigning participants it was possible to set conditions for filtering through the participants in our subject pool. This is what I mean (taken from our previous version Orsee 3.05): https://ibb.co/Y0yvxkG

Now with the new version this list of conditions for the same experiment is empty: https://ibb.co/4NzFR0J

We did not change anything in the database and the problem emerges for every experiment. Just for fun, we re-installed Orsee 3.05 and there the set of conditions works.

Did anybody experienced the same problem? Do we have to change something in the code

of the page to make the filtering work again?

Thanks for your help

Best,

Behnud

**Comment by bgreiner** [comment]
<b>Author: Ben Greiner</b>

Hi Behnud,

This is pretty odd. I have not seen this problem before. My guess is that the issue is with javascript. Have you tried with a different browser?

Also, could you pleae check the Javascript console of your browser for any javascript error messages?

Cheers

/ben

**Comment by bgreiner** [comment]
<b>Author: Ben Greiner</b>

PS: One thing that has changed is how JSON functions are initialized, since PHP changed its code on this some time ago. Is there a chance that you are running a pretty old PHP version on your server?

See also:

<https://github.com/orsee/orsee/commit/da7a7295b02f673f2ef6354c1eddbe0fbf346d53>

Cheers

/ben

**Comment by bgreiner** [comment]
<b>Author: Behnud</b>

Hi Ben,

many thanks for your quick reply. We checked what you said and were able to (I think) narrow down the potential source of the error.

-The error remains no matter which browser (Firefox/Chrome) we use

-The server runs on PHP 7.3.19, so pretty up to date

-In the console however we get the error message \\u201eUncaught SyntaxError: Unexpected token ';'\\u201c. It emerges on the page https://groups.uni-paderborn.de/baer-lab/orsee/admin/options_default_queries.php?type=participants_search_all

In code line 103 of the 3.0.5 version of that page the ptypes are filled (see here: https://ibb.co/k1kyvWZ), but in the same code line of the 3.1.0 version the ptypes are empty (https://ibb.co/d0MRZwt). Maybe this is the reason why the dropdown list is empty?

Any help is much welcomed.

Cheers,

Behnud

**Comment by bgreiner** [comment]
<b>Author: Ben Greiner</b>

So it seems indeed related to the json encoding, The code that produces that line is in tagsets/query.php lines 149-151 (e.g. see here: <https://github.com/orsee/orsee/blob/master/tagsets/query.php>

The question is whether there is a problem in the json data itself ($tmp), or whether the json_encode function does not work.

What would help is if you could just dump the $tmp variable and see what comes out., i.e. before line 149 (i.e. before the script tag) put a

var_dump($tmp);

and then look at the produced page.

Also, are there no errors in the PHP log?

Cheers

/ben

**Comment by bgreiner** [comment]
<b>Author: Behnud</b>

Hi Ben,

thanks again for your help. We checked the $tmp per vardump and the variable is filled correctly (see the picture here, the layout is not so nice, but you can see the information is all there: https://ibb.co/8scpCWM). So this is not the problem.

The problem seems to be the json_encode function. It doesn't parse $var correctly and doesn't return anything. Therefore the list can't be build. This is the error we receive after json_encode($var) is executed (https://ibb.co/VSCvGFB).

For debugging purposes, we managed to get an output for one specific item of the tmp array. This was achieved via:

Line 150:                   console_log_pcds($tmp['noshows_numbercompare']);

function console_log_pcds( $data ){

  echo 'console.log('. json_encode( utf8_encode($data) ) .');';

  echo 'console.log('. json_encode( $data ) .');';

  echo '</script>';

}

The return of Null is when we utf8-encode the data first. If we do it like this, the item gets displayed normally, but if we pass the whole tmp array to the json_encode function, it doesnt work anymore.

Best,

Behnud

**Comment by bgreiner** [comment]
<b>Author: Ben Greiner</b>

Hi,

(utf8_encode() can only be applied to strings but not to an array, so will return NULL.)

Can you force json_encode() to throw an error message? I.e. change line 150 of tagets/query.php to

`echo json_encode($tmp,JSON_THROW_ON_ERROR);`

and then look out for PHP error messages and let me know the result.

Thanks

/ben

**Comment by bgreiner** [comment]
<b>Author: Behnud</b>

Hi Ben,

here are the error logs:

Here: https://ibb.co/4YqDQg6 and below. As you can see in the picture, the second last line of code looks odd.

Logs fuer Gruppe baer-lab seit Sun Nov 29 10:38:14 2020 (maximal 500 Eintraege)

    #1 /upb/groups/baer-lab/public/https/orsee/tagsets/query.php(11): query__echo_form_javascript(Array, '')

    thrown in /upb/groups/baer-lab/public/https/orsee/tagsets/query.php on line 159

    #0 /upb/groups/baer-lab/public/https/orsee/tagsets/query.php(159): json_encode(Array, 4194304)

    #1 /upb/groups/baer-lab/public/https/orsee/tagsets/query.php(11): query__echo_form_javascript(Array, '')

    #2 /upb/groups/baer-lab/public/https/orsee/admin/options_default_queries.php(50): query__show_form(Array, false, '', 'Save query', Array, '', '

    thrown in /upb/groups/baer-lab/public/https/orsee/tagsets/query.php on line 159

Best, Behnud

**Comment by bgreiner** [comment]
<b>Author: Ben Greiner</b>

Mmmh, those messages do not really contain error names/descriptions.

In the meantime, I updated all my dev and running systems to newest versions of PHP/MySQL/Apache, but verything still works there, so I still cannot reproduce the problem.

Let's move this conversation to email. I will put in a solution here and on github once found.

Cheers

/ben
