### ISSUE TITLE
Error sending mail - SQLSTATE[HY093]: Invalid parameter number

### ISSUE THREAD

**Issue by bgreiner** [orsee/orsee#349]
<b>Author: Luca Panaccione</b>

Hello,

We have an problem with the invitations to be sent by mail to the assigned participants of a session.

We have checked that the three conditions mentioned in previous messages (including the session status to "Live") are satisfied.

However, the mail queue is not automatically processed and invitations are not sent to assigned participants.

Moreover, when trying to send invitations via the Regular tasks (cron) section, we get the following error:

Query error: SQLSTATE[HY093]: Invalid parameter number
Query: SELECT * from or_bulk_mail_texts
                WHERE bulk_id= :bulk_id
                AND lang= :tlang

Do you have any idea for how to solve the problem? Any suggestion would be really appreciated!

Thank you very much,
Luca

**Comment by bgreiner** [comment]
<b>Author: Alessandro</b>

Hi Everybody,

i'm Alessandro working in the same team of Luca.
We have analyzed systems log and we share here what we have troubleshooted:

root@orsee-Sapienza:/var/log/apache2# tail -f Orsee_error.log
[Fri Oct 18 12:01:12.914722 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning:  Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 28, referer: https://195.231.0.184/admin/experiment_add_participants.php
[Fri Oct 18 12:01:12.914727 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning:  Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 28, referer: https://195.231.0.184/admin/experiment_add_participants.php
[Fri Oct 18 12:01:12.914743 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning:  Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 27, referer: https://195.231.0.184/admin/experiment_add_participants.php
[Fri Oct 18 12:01:12.914749 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning:  Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 27, referer: https://195.231.0.184/admin/experiment_add_participants.php
[Fri Oct 18 12:01:12.914755 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning:  Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 28, referer: https://195.231.0.184/admin/experiment_add_participants.php
[Fri Oct 18 12:01:12.914761 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning:  Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 28, referer: https://195.231.0.184/admin/experiment_add_participants.php
[Fri Oct 18 13:55:04.690717 2024] [php:warn] [pid 437044] [client 94.32.194.219:22989] PHP Warning:  Undefined variable $edit in /var/www/orsee-orsee_3.2.0/admin/experiment_show.php on line 187, referer: https://195.231.0.184/admin/experiment_my.php
[Fri Oct 18 13:55:04.690744 2024] [php:warn] [pid 437044] [client 94.32.194.219:22989] PHP Warning:  Trying to access array offset on value of type null in /var/www/orsee-orsee_3.2.0/admin/experiment_show.php on line 187, referer: https://195.231.0.184/admin/experiment_my.php
[Fri Oct 18 13:55:30.017976 2024] [php:warn] [pid 202083] [client 94.32.194.219:22994] PHP Warning:  Undefined variable $stmt in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php on line 97, referer: https://195.231.0.184/admin/cronjob_main.php
[Fri Oct 18 13:55:30.018056 2024] [php:error] [pid 202083] [client 94.32.194.219:22994] PHP Fatal error:  Uncaught Error: Call to a member function fetch() on null in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php:142
Stack trace:
#0 /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php(192): pdo_fetch_assoc()
#1 /var/www/orsee-orsee_3.2.0/tagsets/experimentmail.php(114): orsee_query()
#2 /var/www/orsee-orsee_3.2.0/tagsets/experimentmail.php(375): experimentmail__load_bulk_mail()
#3 /var/www/orsee-orsee_3.2.0/tagsets/cronjobs.php(174): experimentmail__send_mails_from_queue()
#4 /var/www/orsee-orsee_3.2.0/admin/cronjob_main.php(19): cron__process_mail_queue()
#5 {main}
  thrown in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php on line 142, referer: https://195.231.0.184/admin/cronjob_main.php

[Fri Oct 18 14:06:30.036692 2024] [php:warn] [pid 151724] [client 94.32.194.219:23054] PHP Warning:  Undefined variable $stmt in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php on line 97, referer: https://195.231.0.184/admin/cronjob_main.php
[Fri Oct 18 14:06:30.037118 2024] [php:error] [pid 151724] [client 94.32.194.219:23054] PHP Fatal error:  Uncaught Error: Call to a member function fetch() on null in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php:142
Stack trace:
#0 /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php(192): pdo_fetch_assoc()
#1 /var/www/orsee-orsee_3.2.0/tagsets/experimentmail.php(114): orsee_query()
#2 /var/www/orsee-orsee_3.2.0/tagsets/experimentmail.php(375): experimentmail__load_bulk_mail()
#3 /var/www/orsee-orsee_3.2.0/tagsets/cronjobs.php(174): experimentmail__send_mails_from_queue()
#4 /var/www/orsee-orsee_3.2.0/admin/cronjob_main.php(19): cron__process_mail_queue()
#5 {main}
  thrown in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php on line 142, referer: https://195.231.0.184/admin/cronjob_main.php

[Fri Oct 18 14:14:19.876521 2024] [php:warn] [pid 202083] [client 94.32.194.219:23152] PHP Warning:  Undefined variable $stmt in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php on line 97, referer: https://195.231.0.184/admin/cronjob_main.php
[Fri Oct 18 14:14:19.876965 2024] [php:error] [pid 202083] [client 94.32.194.219:23152] PHP Fatal error:  Uncaught Error: Call to a member function fetch() on null in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php:142
Stack trace:
#0 /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php(192): pdo_fetch_assoc()
#1 /var/www/orsee-orsee_3.2.0/tagsets/experimentmail.php(114): orsee_query()
#2 /var/www/orsee-orsee_3.2.0/tagsets/experimentmail.php(375): experimentmail__load_bulk_mail()
#3 /var/www/orsee-orsee_3.2.0/tagsets/cronjobs.php(174): experimentmail__send_mails_from_queue()
#4 /var/www/orsee-orsee_3.2.0/admin/cronjob_main.php(19): cron__process_mail_queue()
#5 {main}
  thrown in /var/www/orsee-orsee_3.2.0/tagsets/orsee_mysql.php on line 142, referer: https://195.231.0.184/admin/cronjob_main.php

Many thanks for helping us, in advance!
Regards
Alessandro

**Comment by bgreiner** [comment]
For the error in the first post, I could not reconstruct any situation where this could actually happen in current ORSEE code. The parameters are distinctively set in query and parameter array and then given to the mysql functions. So I am unable to (even theoretically) reconstruct the error. Were there any code changes?

**Comment by bgreiner** [comment]
The error
[Fri Oct 18 12:01:12.914722 2024] [php:warn] [pid 406859] [client 94.32.194.219:41646] PHP Warning: Undefined array key "time,experiment_name" in /var/www/orsee-orsee_3.2.0/tagsets/helpers.php on line 28, referer: https://195.231.0.184/admin/experiment_add_participants.php

was resolved in October '23
https://github.com/orsee/orsee/pull/73

The errors
[Fri Oct 18 13:55:04.690717 2024] [php:warn] [pid 437044] [client 94.32.194.219:22989] PHP Warning: Undefined variable $edit in /var/www/orsee-orsee_3.2.0/admin/experiment_show.php on line 187, referer: https://195.231.0.184/admin/experiment_my.php
[Fri Oct 18 13:55:04.690744 2024] [php:warn] [pid 437044] [client 94.32.194.219:22989] PHP Warning: Trying to access array offset on value of type null in /var/www/orsee-orsee_3.2.0/admin/experiment_show.php on line 187, referer: https://195.231.0.184/admin/experiment_my.php

were also resolved in October '23
https://github.com/orsee/orsee/pull/74

For the 3 pairs of "Undefined variable $stmt" / "Uncaught Error: Call to a member function fetch() on null" I would need to know which query they refer to. If they refer to the query from Post 1, then please see above.
